version: '2'
services:
  web:
    build: ./webStart
    ports:
     - "8080:8080"
    #volumes:
     #- ./BackContent:/usr/local/tomcat/content
    links:
     - redis
     - mongo
     - mysql
     

  redis:
    image: redis

  mongo:
    build: ./mongoStart

  mysql:
    image: mysql
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=123456
