version: '2'
services:
  web:
    build: ./webStart
    ports:
     - "80:8080"
     - "443:443"
     volumes:
     - ./repository:/root/.m2/repository
    depends_on:
     - certbot
    links:
     - redis
     - mongo
     - mysql
    restart: always
  
  certbot:
    image: certbot/certbot
    volumes:
     - ./encrypt:/etc/letsencrypt
    command: renew

  redis:
    image: redis

  mongo:
    image: mongo
    volumes:
     - ./mongoStart:/docker-entrypoint-initdb.d

  mysql:
    image: mysql
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=123456
