version: '2'
services:
  web:
    build: ./webStart
    volumes:
     - ./encrypt:/usr/local/tomcat/conf
    ports:
     - "80:8080"
    depends_on:
     - certbot
    links:
     - redis
     - mongo
     - mysql
    restart: always
  
  certbot:
    image: certbot/certbot
    volumes:
     - ./encrypt:/etc/letsencrypt
    command: renew

  redis:
    image: redis

  mongo:
    build: ./mongoStart

  mysql:
    image: mysql
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=123456
